### ISSUE TITLE
Error error: invalid resource name \"pod/xxxx\": [may not contain '/']

### ISSUE THREAD

**Issue by tiokouBrice** [openshift/openshift-client-python#115]
Hello,
i find and Error when using the follow command: 
- oc.selector('pod/mypodname').object().execute(xxx)

i have the error: 
"err": "error: invalid resource name \"pod/xxxx\": [may not contain '/']\n",

when looking the reason:
i find an error in the openshift/apiobject.py
in the fonction : def execute(.....)

you have to change the parameter qname() to name()

have a nice day..

**Comment by bradmwilliams** [comment]
@tiokouBrice Can you check which version you are running?

I am using version `1.0.17` and do not see a problem with this logic:
``` python
#!/usr/bin/env python

import openshift as oc

if __name__ == '__main__':
    with oc.client_host():
        with oc.timeout(60 * 30):
            with oc.project("my-project"):
                result = oc.selector('pod/chatterbox').object().execute(['echo', 'hello world!'])
                print(result.out())
                exit(0)
```

**Comment by bradmwilliams** [comment]
Can you provide a more complete example of the logic that's producing this failure?
