### ISSUE TITLE
Selector#until_all or Selector#until_any methods do not have a timeout

### ISSUE THREAD

**Issue by m-czernek** [openshift/openshift-client-python#135]
The [until_all](https://github.com/openshift/openshift-client-python/blob/main/packages/openshift/selector.py#L644) method does not have a timeout. Consequently, if the caller does not define a failure function, the method waits indefinitely.

The failure function approach assumes that the caller knows all of the possible issues that could happen with the object. However, this is not always the case.

Would you be open to adding a timeout parameter to the functions?

**Comment by bradmwilliams** [comment]
The library itself relies on a higher level timeout as a ContextManager.  It can be used by adding:
`with oc.timeout(15*60):`
