### ISSUE TITLE
Override context for current kubeconfig

### ISSUE THREAD

**Issue by pehala** [openshift/openshift-client-python#164]
`Context()` class allows to override many options that would be passed as cmdline arguments, like token or server url, but I cannot find a way how to override `--context` cmdline option to enable having one kubeconfig and referencing different contexts within.

Is there a way how to do this currently?

**Comment by bradmwilliams** [comment]
In situations where I have had to switch between contexts in my kubeconfig, I have used this pattern:
```python
import openshift_client as oc

if __name__ == '__main__':
    context1 = {
        'context': 'cluster1',
    }
    context2 = {
        'context': 'cluster2',
    }
    with oc.client_host():
        with oc.timeout(60 * 5):
            for context in [context1, context2]:
                with oc.options(context):
                    with oc.project('my-project'):
                        jobs_list = oc.selector('pods').objects()
                        print(f'Found: {len(jobs_list)} pods in: {context["context"]}')
```

**Comment by bradmwilliams** [comment]
This is also how you can perform operations with elevated privileges, like: https://github.com/openshift/openshift-client-python/blob/bbb925b995f6151e72a5302f5d5a6db7d88666c5/examples/etcd_status.py
