### ISSUE TITLE
Catch missing export options in collection

### ISSUE THREAD

**Issue by omenos** [openshift/openshift-client-python#47]
The following snippets have an issue because the `export` verb in the `oc` utility does not include the flag `--ignore-not-found`. A program will fail because `objects(exportable=True)` will silently pass `True` for the ignore flag and error out the CLI tool.

https://github.com/openshift/openshift-client-python/blob/4c148e0bb623b59c427fd0c0133ca620388f726d/packages/openshift/selector.py#L374-L375

https://github.com/openshift/openshift-client-python/blob/4c148e0bb623b59c427fd0c0133ca620388f726d/packages/openshift/selector.py#L412-L421

A catch as simple as adjusting L374 to `if ignore_not_found and not exportable:` should suffice (though it'd probably be a good idea to log or print that that flag is being ignored). In the long run (if this tool does see future developments), it would be good to see the `export` verb removed in favor of an `--export` argument to pass to get.

**Comment by bradmwilliams** [comment]
The `export` option has been deprecated now, so I have removed the offending code all together(#69).  Closing this issue.
