### ISSUE TITLE
Each log has head string and tail string

### ISSUE THREAD

**Issue by badger1961** [openshift/openshift-client-python#54]
In case users use print_log function each file contains 
start string [logs:begin]xxxt-xx-xxx-01:pod/xxx-xxxxx-xxxxxxxl-d997f557d-vpf8r->pod/xxx-xxxxxxx-xxxxxxxx- f557d-vpf8r(postgresql)========
end string [logs:end]xxxxx-xx-xxxxx-01:pod/xxx-xxxxxx-xxxxxl-d997f557d-vpf8r->pod/xxx-xxxxxx-xxxxxxx-d997f557d-vpf8r(postgresql)========

This is not convenient. For example if log has json format I can load to an editor and format this log as json file. This strings confuse formatter. Commonly speaking I don see real role of this string. This string is  mandatory added in utils module. Can I fix them or anybody use these strings

**Comment by bradmwilliams** [comment]
Hi @badger1961,
The **print_logs** method exists as a convenience method to print out the logs, from all the containers, of the selected resources, in a human readable format.  Without the deliminator messages, it's impossible to distinguish between messages from one container to another.  

You are more than welcome to submit a PR to enhance the existing logic or create a new utility method, all together, to provide the messages as you describe above.

**Comment by bradmwilliams** [comment]
Closing this issue because that code is working as expected.
