### ISSUE TITLE
image mirror

### ISSUE THREAD

**Issue by lioramilbaum** [openshift/openshift-client-python#61]
Please add the ability of executing: 'image mirror'

**Comment by bradmwilliams** [comment]
Hi @lioramilbaum,
Have you looked into calling `image mirror` via `oc.invoke()`?

For instance:
     `oc.invoke('image', cmd_args=['mirror', 'myregistry.com/myimage:latest', 'myregistry.com/myimage:stable'])`

**Comment by lioramilbaum** [comment]
Thanks @bradmwilliams. It is a good solution for my request.
