### ISSUE TITLE
How is this client different from others?

### ISSUE THREAD

**Issue by dbazhal** [openshift/openshift-client-python#66]
For example there already is https://github.com/openshift/openshift-restclient-python and I can't imagine why there is two of them and which one should i use.

**Comment by bradmwilliams** [comment]
This particular client is best suited for anywhere that logic relies heavily on the usage of the `oc` tool.  We have tried to convey this in the repository [Overview](https://github.com/openshift/openshift-client-python/blob/main/README.md#overview) section:

Please take a look around the [examples](https://github.com/openshift/openshift-client-python/tree/main/examples) for some basic usage references and patterns.

If you have any specific questions, concerns, please let us know!
