### ISSUE TITLE
Change/update package namespace

### ISSUE THREAD

**Issue by bradmwilliams** [openshift/openshift-client-python#75]
It has come to our attention that the "openshift" namespace is being used by another Openshift python project:
[openshift](https://pypi.org/project/openshift/) -> [openshift-restclient-python](https://github.com/openshift/openshift-restclient-python)

Each project provides their own version of __init__.py, each with conflicting setup/configuration.  Because of this, these 2 projects can not happily co-exist together in the same environment

Opening this issue to re-home our package to allow for these packages to co-exist.

**Comment by alekonko** [comment]
what's new?

**Comment by ralberrto** [comment]
Hi there they're still unable to coexist... Was the project abandoned?

**Comment by ralberrto** [comment]
Hi there, these two packages are still unable to coexist is there any information on whether this was put off or aborted?

**Comment by bradmwilliams** [comment]
Hi @ralberrto,
This project is still actively being used and updated as needed.  Unfortunately, we've been focusing on other priorities.  I have made the necessary changes and will get them rolled out shortly.  Please note, this is a breaking change and therefore will be rolled out as version `2.0.0`.  The new namespace will be `openshift_client`.

**Comment by ralberrto** [comment]
Thank you for replying! Is the development team from RedHat mostly? Just curious...

**Comment by bradmwilliams** [comment]
Yes
