### ISSUE TITLE
Allow custom subclasses of APIObject for Selector.object() and Selector.objects()

### ISSUE THREAD

**Issue by pehala** [openshift/openshift-client-python#82]
## Overview
It would be great if `Selector.objects()` and `Selector.object()` would allow to specifiy which class it should create. This can be useful when you have custom class on top of APIObject for helping with managing said resource.

## Example
```python
oc.selector("pods").objects(class=DeploymentConfig) ~> List[DeploymentConfig]
oc.selector("pods").object(class=DeploymentConfig) ~> DeploymentConfig
oc.selector("pods").object() ~> APIObject
```

I think I could implement this if you would like this to be added.

**Comment by bradmwilliams** [comment]
@pehala Can you take a look at #83 and see if this meets your expectations?

**Comment by bradmwilliams** [comment]
@pehala I have merged the changes.  They are available directly or from PyPI: https://pypi.org/project/openshift-client/1.0.9/

**Comment by pehala** [comment]
Thanks!
